export default async function handler(req, res) {
  if (req.method !== 'GET') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const privacyPolicy = {
    company: "Alfa Systems LLC",
    effective_date: "2025-08-03",
    version: "2.5",
    contact: {
      email: "privacy@alfasystems.com",
      phone: "+1 307 222 1996",
      address: "30 N Gould St. Suite B, Sheridan, WY 82801, USA"
    },

    sections: {
      who_we_are: {
        title: "Who We Are",
        content: "Alfa Systems LLC ('Alfa Systems', 'we', 'us', 'our') is the provider of alfaOne, a talent-evaluation platform (the 'Platform') that combines AI review with human expertise to help employers identify qualified candidates.",
        registered_address: "30 N Gould St. Suite B, Sheridan, WY 82801, USA",
        website: "https://alfasystems.com"
      },

      scope: {
        title: "Scope of This Policy",
        content: "This Privacy Policy describes how we collect, use, disclose and protect personal data when you visit https://alfasystems.com (the 'Site'), use our alfaOne hiring-assessment platform ('alfaOne' or the 'Platform'), or otherwise interact with us (collectively, the 'Services')."
      },

      data_collected: {
        title: "The Data We Collect",
        categories: [
          {
            category: "Identification",
            examples: "name, email, phone, account ID",
            collected_from: "candidates, clients",
            mandatory: true
          },
          {
            category: "Assessment content",
            examples: "video/audio recordings, written answers, code snippets",
            collected_from: "candidates",
            mandatory: true
          },
          {
            category: "AI review metadata",
            examples: "timestamps, language vectors, feature scores",
            collected_from: "generated by Platform",
            mandatory: true
          },
          {
            category: "Usage data",
            examples: "IP, device type, browser, cookies",
            collected_from: "website visitors",
            mandatory: false
          },
          {
            category: "Client billing data",
            examples: "contact name, billing address, VAT, payment tokens",
            collected_from: "clients",
            mandatory: true
          },
          {
            category: "Support records",
            examples: "chat transcripts, tickets, call recordings",
            collected_from: "anyone contacting support",
            mandatory: false
          }
        ],
        special_category_note: "We do not request or knowingly process special-category data (e.g., racial or ethnic origin) unless required by law and with explicit consent."
      },

      legal_bases: {
        title: "Why We Process Data & Our Legal Bases (GDPR Art 6)",
        purposes: [
          {
            purpose: "Provide and secure the Services",
            legal_basis: "Performance of contract (Art 6 (1)(b))",
            details: "Create candidate workspaces, deliver AI reviews, administer accounts"
          },
          {
            purpose: "Improve accuracy & fairness",
            legal_basis: "Legitimate interests (Art 6 (1)(f))",
            details: "Aggregate, anonymise data to refine review models & detect bias"
          },
          {
            purpose: "Handle payments & invoices",
            legal_basis: "Performance of contract",
            details: "Process transactions for paid subscriptions"
          },
          {
            purpose: "Marketing to business contacts",
            legal_basis: "Consent (opt-in) or Legitimate interests",
            details: "Send product updates; opt-out any time"
          },
          {
            purpose: "Legal & compliance",
            legal_basis: "Legal obligation (Art 6 (1)(c))",
            details: "Retain records, respond to lawful requests"
          }
        ]
      },

      ai_review: {
        title: "How Our AI Review Works",
        description: "The AI review analyses language patterns, topic coverage and time management in assessment responses. It outputs recommendations only; qualified human reviewers make all final hiring decisions.",
        manual_review_available: true,
        right_to_contest: "You may contest the outcome of an AI review, request human intervention or express your views under GDPR Art 22 and equivalent laws. Contact privacy@alfasystems.com to exercise this right."
      },

      data_sharing: {
        title: "How We Share Data",
        policy: "We do not sell personal data. We share it only:",
        scenarios: [
          "With service providers (e.g., cloud hosting, analytics, email)—all bound by written data-processing agreements",
          "Within the Alfa Systems group (if subsidiaries exist) for legitimate internal purposes",
          "When required by law (court orders, lawful government requests)",
          "In business transfers (merger, acquisition) with notice to affected individuals"
        ],
        subprocessors_url: "https://alfasystems.com/subprocessors",
        subprocessors_notice_period: "30 days before any new provider gains access"
      },

      international_transfers: {
        title: "International Transfers",
        storage_locations: ["European Economic Area (EEA)", "United States"],
        safeguards: [
          "Standard Contractual Clauses (SCCs) approved by the European Commission",
          "UK Addendum to the SCCs",
          "Adequacy decisions (e.g., EU–US Data Privacy Framework)"
        ],
        safeguards_available_on_request: true
      },

      data_retention: {
        title: "Data Retention",
        periods: [
          {
            category: "Assessment video/audio",
            period: "180 days after assessment completion (unless client requests shorter/longer)"
          },
          {
            category: "AI review metadata",
            period: "2 years, then aggregated & anonymised"
          },
          {
            category: "Client account data",
            period: "Duration of contract + 7 years for tax/audit"
          },
          {
            category: "Marketing contact info",
            period: "Until you opt-out or 3 years of inactivity"
          }
        ],
        legal_retention_note: "We may retain data longer if required by law or to establish, exercise or defend legal claims."
      },

      your_rights: {
        title: "Your Rights",
        rights: [
          "Access, correct or delete your personal data",
          "Restrict or object to processing",
          "Data portability",
          "Withdraw consent at any time",
          "Lodge a complaint with a supervisory authority"
        ],
        exercise_contact: "privacy@alfasystems.com",
        response_time: "30 days"
      },

      security: {
        title: "Security",
        measures: [
          "TLS/SSL encryption in transit and AES-256 at rest",
          "Multi-factor authentication for admin accounts",
          "Role-based access controls",
          "Annual penetration testing and SOC 2 Type II audits"
        ]
      },

      cookies: {
        title: "Cookies & Similar Technologies",
        types: [
          {
            type: "Essential cookies",
            purpose: "session authentication",
            consent_required: false
          },
          {
            type: "Analytics cookies",
            purpose: "Google Analytics 4 - measure traffic",
            consent_required: true
          }
        ],
        cookie_policy_url: "https://alfasystems.com/cookie-policy"
      },

      california_privacy: {
        title: "California Privacy Notice (CPRA)",
        rights: [
          "Know what personal information we collect and how we use it",
          "Delete personal information (subject to exceptions)",
          "Correct inaccurate information",
          "Opt-out of cross-context behavioural advertising (we do not 'sell' personal information)",
          "Limit use of sensitive personal information (we only use it to provide the Services)"
        ],
        contact: {
          email: "cpra@alfasystems.com",
          phone: "+1 307 222 1996"
        }
      },

      children_privacy: {
        title: "Children's Privacy",
        age_limit: 16,
        policy: "The Services are not directed to children under 16. We do not knowingly collect personal data from children. If we learn we have, we will delete it immediately."
      },

      policy_changes: {
        title: "Changes to This Policy",
        notice_period: "30 days",
        notification_method: "email to clients",
        policy: "We may update this Policy from time to time. We will post the revised version with a new effective date and notify clients via email at least 30 days before the change takes effect if it materially affects your rights."
      }
    },

    full_text_url: "https://alfasystems.com/privacy-policy"
  };

  return res.status(200).json(privacyPolicy);
}
